"""
Emit the expanded Columbia courses as a TypeScript module.

Skill tags here are a fallback only. When an API key is present the relevance
pass reads each description against the actual posting and quotes the sentence
that proves the match, which is far better than any fixed vocabulary. But a
deployment with no key still has to do something, so each course gets tags
derived by looking for a term in its own description and keeping the sentence
the term appeared in as the evidence. The evidence is therefore genuinely from
the catalog, which is the only property that matters.
"""
import json, re

VOCAB = {
  "Machine learning": ["machine learning", "supervised learning", "statistical learning"],
  "Deep learning": ["deep learning", "neural network", "neural networks"],
  "NLP": ["natural language", "computational linguistics", "speech recognition"],
  "Computer vision": ["computer vision", "image processing", "visual recognition"],
  "Robotics": ["robot", "robotics", "manipulator"],
  "Reinforcement learning": ["reinforcement learning", "markov decision"],
  "Artificial intelligence": ["artificial intelligence"],
  "Algorithms": ["algorithm design", "analysis of algorithms", "algorithmic", "sorting and searching"],
  "Data structures": ["data structures", "data types and structures"],
  "Databases": ["database", "relational model", "query", "sql"],
  "Distributed systems": ["distributed system", "distributed comput", "consensus", "replication"],
  "Operating systems": ["operating system", "process management", "concurrency"],
  "Computer networks": ["computer network", "networking", "tcp", "internet protocol"],
  "Security": ["security", "vulnerabilit", "malware", "intrusion"],
  "Cryptography": ["cryptograph", "encryption", "cipher"],
  "Compilers": ["compiler", "parsing", "code generation", "translators"],
  "Computer architecture": ["computer architecture", "microarchitecture", "instruction set"],
  "Computer graphics": ["computer graphics", "rendering", "ray trac"],
  "Software engineering": ["software engineering", "software development", "version control", "testing and debugging"],
  "Linear algebra": ["linear algebra", "matrices", "eigenvalue"],
  "Probability": ["probability", "random variable", "stochastic"],
  "Statistics": ["statistic", "regression", "hypothesis test"],
  "Optimization": ["optimization", "linear programming", "convex"],
  "Parallel computing": ["parallel comput", "gpu", "multicore", "concurrent programming"],
  "Cloud computing": ["cloud comput", "virtualization", "containers"],
  "Java": ["in java", "java programming"],
  "C": ["c programming language"],
  "C++": ["c++"],
  "Python": ["python"],
  "Human computer interaction": ["human-computer interaction", "user interface", "usability"],
  "Game theory": ["game theory", "mechanism design", "equilibri"],
  "Formal verification": ["formal verification", "model checking", "theorem prov"],
  "Computational biology": ["genomic", "computational biology", "bioinformatic"],
  "Theory of computation": ["automata", "turing machine", "computability", "np-complete"],
}

def sentences(text):
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s.strip()) > 15]

def tag(desc):
    out, seen = [], set()
    sents = sentences(desc)
    low = [s.lower() for s in sents]
    for skill, terms in VOCAB.items():
        for t in terms:
            hit = next((i for i, s in enumerate(low) if t in s), None)
            if hit is not None and skill not in seen:
                seen.add(skill)
                out.append({"skill": skill, "evidence": sents[hit]})
                break
    return out[:6]

# ── Overlap rules, kept apart from the course rows ───────────────────────────
#
# "Not to be taken in addition to MATH UN2010" is a fact about a course that has
# nothing to do with whether its description parsed. Emitting it inside the
# course row meant it was thrown away with the row: Honors Linear Algebra has no
# parseable description, so it was skipped, so the rule vanished, so a plan
# happily scheduled both linear algebra courses. The rules travel separately now
# and apply to hand-written courses too.
def _cid(code):
    return "COLUMBIA:" + code.replace(" ", "")

overlaps = {}
for c in json.load(open("ingest/columbia-parsed.json")):
    if c.get("overlapsWith"):
        overlaps.setdefault(_cid(c["code"]), [])
        for o in c["overlapsWith"]:
            if _cid(o) not in overlaps[_cid(c["code"])]:
                overlaps[_cid(c["code"])].append(_cid(o))

courses = json.load(open("ingest/columbia-expanded.json"))
for c in courses:
    c["skills"] = tag(c["description"])

body = ",\n".join("  " + json.dumps(c, ensure_ascii=False) for c in courses)
ts = f'''import type {{ Course }} from "@/lib/types";

/**
 * Every Columbia course the bulletin publishes a description for.
 *
 * Generated by `python3 ingest/emit-catalog.py` from the pages committed under
 * `data/snapshots/courses/`, one file per course, fetched from the university's
 * own bulletin. Do not edit by hand: rerun the script.
 *
 * These carry `verified: false`, which is not a formality. The prerequisite
 * trees were parsed from the bulletin's own grammar rather than read by a
 * person, so the UI shows an "ask your advisor" note against anything the
 * parser could not turn into a course id, and against any prerequisite naming a
 * course this catalog does not hold. The hand-checked courses in `columbia.ts`
 * carry `verified: true` and take precedence over anything here.
 *
 * The skill tags are a no-API-key fallback. With a key, relevance reads these
 * same descriptions against the actual posting and quotes the proving sentence,
 * which is strictly better. Either way the evidence comes from the catalog.
 */
export const COLUMBIA_EXTRA: Course[] = [
{body},
];

/**
 * Courses the bulletin says cannot both count, keyed by course id.
 *
 * Read from the same snapshots, from sentences like "Not to be taken in
 * addition to MATH UN2010" and "may not receive credit for both COMS W4771 and
 * W4776". Kept out of the rows above so that a course whose description failed
 * to parse still contributes its rule.
 */
export const COLUMBIA_OVERLAPS: Record<string, string[]> = {json.dumps(overlaps, indent=2, ensure_ascii=False)};
'''
open("data/columbia-extra.ts", "w").write(ts)
tagged = sum(1 for c in courses if c["skills"])
print(f"emitted {len(courses)} courses to data/columbia-extra.ts")
print(f"with fallback skill tags: {tagged}")
