// Generated by scripts/gen-pipeline-version.mjs before every dev and build.
// Do not edit by hand: it is a content hash of the prompts, the solver and the
// catalog, and its whole job is to change when they do.
export const PIPELINE_VERSION = "8f31c5429c0f";
