import { readFileSync } from "fs";
import { solve } from "../lib/solver";
const base = JSON.parse(readFileSync("scratch/solve-payload.json", "utf8"));
const drop = (ids: string[]) => Object.fromEntries(Object.entries(base.relevance).filter(([k]) => !ids.includes(k)));
let t0 = Date.now();
let r = solve({ ...base, relevance: drop(["COLUMBIA:COMSW4152"]) }, 12000, 3_000_000);
console.log(`minus 4152: ok=${r.ok} in ${Date.now()-t0}ms ${r.ok?`covered=${r.plans[0]?.skillsCovered?.length} plans=${r.plans.length}`:""}`);
t0 = Date.now();
r = solve({ ...base, relevance: drop(["COLUMBIA:COMSW4152","COLUMBIA:COMSW4181"]) }, 12000, 3_000_000);
console.log(`minus 4152+4181: ok=${r.ok} in ${Date.now()-t0}ms ${r.ok?`covered=${r.plans[0]?.skillsCovered?.length}`:""}`);
